"""ACCEPTANCE TEST for phase 5 -- the step that does the 100:1 selection.

Filter 1 has had an acceptance test since phase 2. Phase 5 -- the step that
turns 402 candidates into the three to five names entered in the watchlist --
had none until 2026-08-22. The review of that date put it plainly: a
refactoring that quietly reordered ``EBIT_ALIASES``, or that picked
``Total Current Liabilities`` where ``Current Liabilities`` was present, passed
all 954 tests, and what changed was exactly which five names the owner spends
hours on.

WHAT IS FROZEN AND WHAT IS NOT.

Frozen: the INPUTS. ``tests/fixtures/ranking-acceptance/`` holds the statement
lines and quote-summary fields of all 394 post-collapse candidates of the
2026-08-21 run, the three ticker statuses, and the twelve exchange rates that
run recorded -- so the price leg is replayed rather than re-fetched and the
answer does not move with the market.

NOT frozen: the EXPECTED OUTPUT. The five names and their placings are written
out longhand below. They are not generated by anything, and
``tools/freeze_ranking_acceptance.py`` deliberately does not produce them. A
test whose expectation is regenerated from the code it tests proves only that
the code agrees with itself. If this fails, the question is what changed in the
key -- not how to refresh the numbers.

The fixture carries the alias ALTERNATIVES as well as the aliases in use --
``Operating Income`` beside ``EBIT``, ``Current Assets`` beside
``Total Assets``, and ``EBITDA``, the substitution E5 forbade -- so a silent
swap changes this answer instead of changing nothing.

RE-FROZEN 2026-08-26 (SCREENER-REVIEW-3 build, item 1). The enterprise value
is no longer the vendor's ``enterpriseValue``; it is built from the vendor's
share count re-priced at the settled close plus ``totalDebt - totalCash``
(ranking rule 8). The fixture therefore gained ``regularMarketPrice``,
``totalDebt``, ``totalCash`` and ``closes-2026-08-21.csv``; the series,
status and fx files are byte-identical to the 2026-08-23 freeze, and the
population is the same 394. The pins below were re-derived by plain
arithmetic over the CSVs (scratch ``pins.py``, not this module) and agree
with it on every place. What item 1 moved: ROCK-B.CO 6 -> 5 and BETS-B.ST
5 -> 6; FGR.PA 9 -> 8 past NREST.ST; LUG.ST (15) and KCR.HE (17) enter the
top twenty, AD.AS (22) leaves it, and KMAR.OL -- ranked before on a vendor
enterprise value although the store holds NO marketCap for it -- is
unrankable; CVNA, LISP.SW and SILEX.ST, whose VENDOR figure the L2 bound had
refused, regain a yield from the parts (LISP.SW: 4.3%, place 127).

RE-PINNED 2026-08-26 AGAIN (item 9, FRAMEWORK-EDITS E43). The quality leg
is EBIT / total assets -- the same EBIT the price leg divides, on the same
basis -- and ``Gross Profit`` is read by nothing. The fixture files are
unchanged (the lines were always there); the pins were re-derived
independently (``pins.py EBIT-E43``) and agree with the module on every
place. What E43 moved: UHS 1 -> 24 (12.8% against the vendor's 101.1%),
AFRY.ST 11 -> 190 (5.1%), FGR.PA 8 -> 123, BUCN.SW 10 -> 50; RMV.L (9),
ULTA (40), ITV.L (76) and SWEC-B.ST (127), for which the vendor carried no
gross profit, regain a quality leg; AUTO.L and BAB.L, K6's two mixed-period
refusals under E6, resolve because EBIT and total assets share a period
end (AUTO.L enters at 4); MONC.MI, whose EBIT is one figure in two units,
now has no quality leg either. 322 -> 328 on both legs, 56 -> 50 on yield
alone; the top five is LULU, DECK, PNDORA.CO, AUTO.L, NVR.
"""

from __future__ import annotations

import csv
import json
from datetime import date
from pathlib import Path

import pytest

from vss.fundamentals import FieldValue, SeriesPoint, TickerFundamentals
from vss.fx import FxTable, Rate, read_manifest_rates
from vss.ranking import (
    EV_IMPOSSIBLE_NOTE,
    QUALITY_INVESTMENT,
    QUALITY_MISSING,
    QUALITY_MIXED_PERIODS,
    QUALITY_OK,
    QUALITY_SECTOR,
    QUALITY_STALE,
    rank_candidates,
)

FIXTURES = Path(__file__).resolve().parent / "fixtures" / "ranking-acceptance"

#: A point-in-time vendor snapshot (2026-08-21), not redistributed and not
#: rebuildable -- see tests/fixtures/VENDOR-DATA.json.
pytestmark = pytest.mark.skipif(
    not (FIXTURES / "closes-2026-08-21.csv").exists(),
    reason="needs the owner's 2026-08-21 screener snapshot, which is vendor "
           "data and cannot be refetched")
ASOF = date(2026, 8, 21)
#: The store was fetched on Saturday 2026-08-22 (17:24), after every market
#: had closed on the Friday. That is the date totalDebt and totalCash carry,
#: and it is why the frozen ``regularMarketPrice`` IS the 2026-08-21 settled
#: close: the vendor's marketCap embedded no other price at that hour. See
#: tools/freeze_ranking_acceptance.py.
FETCHED = date(2026, 8, 22)


class Candidate:
    def __init__(self, ticker: str):
        self.ticker = ticker


def load_closes() -> dict[str, tuple[date, float]]:
    """The settled close of every candidate on 2026-08-21, from the price
    snapshot -- the price rule 8 strikes every yield on."""
    return {
        row["ticker"]: (date.fromisoformat(row["close_date"]), float(row["close"]))
        for row in csv.DictReader((FIXTURES / f"closes-{ASOF}.csv").open(encoding="utf-8"))
    }


def load() -> tuple[list[Candidate], dict[str, TickerFundamentals], FxTable]:
    """The frozen 2026-08-21 candidate set, exactly as phase 5 received it."""
    series: dict[str, list[SeriesPoint]] = {}
    for row in csv.DictReader((FIXTURES / f"series-{ASOF}.csv").open(encoding="utf-8")):
        series.setdefault(row["ticker"], []).append(
            SeriesPoint(row["ticker"], row["line"],
                        date.fromisoformat(row["period_end"]),
                        float(row["value"]), row["statement"],
                        # THE FIXTURE IS THE VENDOR PATH'S OWN OUTPUT, frozen
                        # from the 2026-08-21 fundamentals store. That path
                        # asks for `income_stmt` and `balance_sheet`, which
                        # ARE the annual statements, so twelve months is what
                        # was fetched -- the same declaration `snapshot.
                        # read_fundamentals` makes for the same rows, and not
                        # a fact about this test. E13 refuses to rank a flow
                        # line whose length is unrecorded, so leaving it off
                        # here would make the frozen answer unreachable for a
                        # reason that has nothing to do with the key.
                        12 if row["statement"] == "income" else None)
        )
    fields: dict[str, list[FieldValue]] = {}
    for row in csv.DictReader((FIXTURES / f"fields-{ASOF}.csv").open(encoding="utf-8")):
        fields.setdefault(row["ticker"], []).append(
            FieldValue(row["ticker"], row["name"], row["status"],
                       number=float(row["number"]) if row["number"] else None,
                       text=row["text"] or None)
        )
    records: dict[str, TickerFundamentals] = {}
    tickers: list[str] = []
    for row in csv.DictReader((FIXTURES / f"status-{ASOF}.csv").open(encoding="utf-8")):
        ticker = row["ticker"]
        tickers.append(ticker)
        records[ticker] = TickerFundamentals(
            ticker, row["status"], 1, 3,
            tuple(fields.get(ticker, ())), tuple(series.get(ticker, ())),
            error=row["error"] or None,
        )

    stored = json.loads((FIXTURES / f"fx-{ASOF}.json").read_text(encoding="utf-8"))
    table = FxTable()
    for pair, entry in stored["fx"].items():
        table.rates[pair] = Rate(pair, float(entry["rate"]),
                                 date.fromisoformat(entry["as_of"]), entry["source"])
    return [Candidate(t) for t in sorted(tickers)], records, table


def listed_investment_companies() -> frozenset[str]:
    """E46's committed list, as the chain reads it."""
    from vss.filters import INVESTMENT_COMPANIES_PATH, load_investment_companies

    return load_investment_companies(FIXTURES.parents[2] / INVESTMENT_COMPANIES_PATH)


def rank_frozen(candidates, records, table):
    return rank_candidates(candidates, records, table, ASOF,
                           closes=load_closes(), fetched=FETCHED,
                           investment_companies=listed_investment_companies())


@pytest.fixture(scope="module")
def ranked():
    candidates, records, table = load()
    return rank_frozen(candidates, records, table)


# --- the fixture itself ----------------------------------------------------


def test_the_frozen_candidate_set_is_the_one_the_run_ranked():
    candidates, records, table = load()
    assert len(candidates) == 394, "the fixture is not the 2026-08-21 candidate set"
    assert len(load_closes()) == 394, "every candidate must carry its settled close"
    assert len(table.rates) == 12
    assert {r.as_of for r in table.rates.values()} == {date(2026, 8, 21),
                                                      date(2026, 8, 22)}, \
        "the frozen rates lost the two-date evidence K7 was found on"


def test_the_fixture_carries_the_alias_alternatives_and_the_forbidden_line():
    """Otherwise a swap in EBIT_ALIASES would change nothing here and this
    test would not be the net it claims to be."""
    lines = {row["line"] for row in
             csv.DictReader((FIXTURES / f"series-{ASOF}.csv").open(encoding="utf-8"))}
    assert {"EBIT", "Operating Income"} <= lines
    assert {"Gross Profit", "Total Assets"} <= lines
    assert {"Current Assets", "Current Liabilities", "Net PPE"} <= lines
    assert "EBITDA" in lines, "the forbidden substitution is not in the fixture"
    fields = {row["name"] for row in
              csv.DictReader((FIXTURES / f"fields-{ASOF}.csv").open(encoding="utf-8"))}
    assert {"marketCap", "regularMarketPrice", "totalDebt", "totalCash"} <= fields, \
        "the parts the enterprise value is built from must all be frozen (rule 8)"
    assert "enterpriseValue" in fields, \
        "the vendor's memo must be frozen too, so reading it again changes the answer"


def test_the_frozen_fetch_day_quote_is_the_vendors_close_of_the_run_date():
    """The 2026-08-21 store predates ``regularMarketPrice``. It was fetched on
    Saturday 2026-08-22, so its marketCap embeds the Friday close -- which the
    price snapshot does NOT hold for European names (their newest bar is
    08-20, E11's finding). The freeze tool took the vendor's history close of
    08-21 instead and said so; FGR.PA's 118.00 on 11,564m gives the vendor's
    own 98.0m shares back, to the count."""
    _, records, _ = load()
    fgr = records["FGR.PA"]
    assert fgr.value("regularMarketPrice") == pytest.approx(118.0)
    note = next(f.text for f in fgr.fields if f.name == "regularMarketPrice")
    assert "yfinance history" in note and "2026-08-22T17:24" in note
    assert fgr.value("marketCap") / 118.0 == pytest.approx(98.0e6, rel=1e-3)
    assert load_closes()["FGR.PA"] == (date(2026, 8, 20), pytest.approx(117.65, abs=0.01))


# --- the answer ------------------------------------------------------------
#
# Worked out from the frozen figures, not regenerated. Read as:
#   place  ticker      sum  quality  yield   GP/TA     EY

TOP_FIVE = [
    (1, "LULU",       25, 19,  6, 0.2614, 0.1538),
    (2, "DECK",       27,  8, 19, 0.3425, 0.1112),
    (3, "PNDORA.CO",  43, 18, 25, 0.2629, 0.1063),
    (4, "AUTO.L",     46,  3, 43, 0.5730, 0.0914),
    (5, "NVR",        46, 13, 33, 0.2884, 0.0997),
]

#: The yields fell across the board when the alias set was reordered onto
#: meaning (L3) -- UHS 13.5% -> 12.7%, DECK 11.7% -> 11.1% -- which is the
#: whole point of the reorder: it is the as-filed operating income instead of
#: a label that runs higher for two names in three. Rule 8 (2026-08-26) then
#: moved every yield again, by whatever the vendor's embedded price was from
#: the settled close: UHS 12.7% -> 12.8%, BETS-B.ST 22.5% -> 24.8%. And E43
#: (2026-08-26) replaced the quality numerator: the placings in column four
#: are EBIT / total assets, and the yield placings moved with the population.

#: The next fifteen, pinned as (place, ticker, sum, quality, yield). The two
#: legs share a numerator under E43, so the alias test at the bottom moves
#: the top FIVE as well as 319 of 328 places. A net drawn at five would
#: still miss most of what a regression does.
TOP_TWENTY = TOP_FIVE + [
    ( 6, "NHY.OL",     49, 47,   2),
    ( 7, "BETS-B.ST",  50, 49,   1),
    ( 8, "NOVO-B.CO",  70, 25,  45),
    ( 9, "RMV.L",      74,  1,  73),
    (10, "ZZ-B.ST",    74, 26,  48),
    (11, "NREST.ST",   75, 21,  54),
    (12, "CTSH",       79, 61,  18),
    (13, "ROCK-B.CO",  82, 62,  20),
    (14, "ADBE",       87, 12,  75),
    (15, "KAR.ST",     87, 72,  15),
    (16, "RKT.L",      87, 58,  29),
    (17, "LUG.ST",     93,  2,  91),
    (18, "FRES.L",     95, 11,  84),
    (19, "AOS",        97, 27,  70),
    (20, "AAF.L",     107, 73,  34),
]

#: The two-legged population is 328 under E43: the four names the vendor
#: carried no gross profit for (RMV.L, ITV.L, SWEC-B.ST, ULTA) and the two
#: K6 refused as mixed (AUTO.L, BAB.L) join it; MONC.MI, whose EBIT is one
#: figure in two units, leaves the quality leg too; KMAR.OL -- which the
#: vendor's enterpriseValue had priced although the store holds no marketCap
#: for it -- has no yield; PLUS.L, CVNA, LISP.SW and SILEX.ST, refused by L2
#: on the vendor field, rank on the parts. Derived independently from the
#: frozen CSVs, not regenerated from the module under test.
SECTIONS = {"both legs": 326, "yield only": 52, "unrankable": 11, "stale": 5}
#: E46 (item 12): two listed investment companies sat on the two-legged list
#: -- LATO-B.ST and PRX.AS -- and move to the yield-only section. Neither
#: outranked a top-twenty name on either leg, so the twenty placings above
#: are unchanged; the sections and the states are not.

#: The staleness gate measures the age of the rows the key ACTUALLY READS
#: (L4), so two names join the three the record-level flag already caught.
#: Neither of them is in the top twenty, and the placings above are unmoved by
#: their removal -- SHL.DE stood at 246, below every name pinned here on both
#: legs. What changes is the population and the counts.
STALE = ["BWY.L", "COLO-B.CO", "CSG.AS", "ERIE", "SHL.DE"]

#: Names whose net cash (totalCash - totalDebt) exceeds their total assets
#: under rule 8's construction: NONE of the 394. The four the bound refused
#: while it judged the vendor's enterpriseValue are listed so the test can
#: show they were artefacts of that field and not of the companies.
EV_REFUSED: list[str] = []
VENDOR_EV_REFUSED = ["CVNA", "LISP.SW", "PLUS.L", "SILEX.ST"]

#: No mixed-period state remains on this population under E43 -- both
#: quality lines come from one statement date for every name -- and the one
#: input-missing name is MONC.MI (EBIT DATA MISSING on the unit conflict).
STATES = {QUALITY_OK: 327, QUALITY_SECTOR: 59, QUALITY_INVESTMENT: 2,
          QUALITY_STALE: 5, QUALITY_MISSING: 1}


def test_the_top_five_is_what_it_was(ranked):
    """The names phase 6 would enter as PIPELINE. This is the whole point."""
    assert [r.ticker for r in ranked.main[:5]] == [row[1] for row in TOP_FIVE]


def test_every_placing_and_both_ratios_in_the_top_five(ranked):
    """The names alone would survive a change that moved every number.

    Pinning the rank sum, both placings and both ratios means a mis-picked
    balance post has to reproduce five figures to slip through.
    """
    for (place, ticker, combined, quality, yield_, gpta, ey) in TOP_FIVE:
        item = ranked.main[place - 1]
        assert item.ticker == ticker
        assert item.combined == combined
        assert item.quality_rank == quality
        assert item.ey_rank == yield_
        assert item.scored.operating_profitability == pytest.approx(gpta, abs=5e-4)
        assert item.scored.earnings_yield == pytest.approx(ey, abs=5e-4)


def test_the_top_twenty_is_what_it_was(ranked):
    """Places 13 and 14 share a sum of 88, and 18, 19 and 20 share 115 -- all
    separated by the tie rule, alphabetically -- so this also pins E5(d),
    now over a three-way tie rather than a two-way one."""
    for row in TOP_TWENTY:
        place, ticker, combined, quality, yield_ = row[:5]
        item = ranked.main[place - 1]
        assert (item.ticker, item.combined, item.quality_rank, item.ey_rank) == \
            (ticker, combined, quality, yield_), f"place {place} moved"


def test_the_sections_are_the_sizes_they_were(ranked):
    assert len(ranked.main) == SECTIONS["both legs"]
    assert len(ranked.yield_only) == SECTIONS["yield only"]
    assert len(ranked.unrankable) == SECTIONS["unrankable"]
    assert len(ranked.stale) == SECTIONS["stale"]


def test_every_reason_a_candidate_has_no_quality_leg_is_the_count_it_was(ranked):
    assert ranked.reason_counts() == STATES


def test_the_stale_names_are_the_ones_whose_own_ranked_lines_are_too_old(ranked):
    """Three the record-level flag caught, two the key-level gate caught (L4).

    SHL.DE reads its gross profit, total assets and EBIT from 2024-09-30, 690
    days before the run, and stood at rank 246 with status OK because Net PPE
    and Ordinary Shares Number carried 2025-09-30. COLO-B.CO is the same 690
    days old and was excluded. ERIE is the other one, and it is in the section
    the review's own measurement did not cover: its 2025-12-31 EBIT row is
    empty, so its yield was formed from a 2024-12-31 EBIT -- 598 days -- and
    it was ranked on one leg among the sector-exempt names.
    """
    assert [s.ticker for s in ranked.stale] == STALE
    for ticker in ("SHL.DE", "ERIE"):
        assert "the lines this key reads" in ranked.scored[ticker].note
    assert ranked.scored["SHL.DE"].note.endswith("690 days before 2026-08-21")
    assert ranked.scored["ERIE"].note.endswith("598 days before 2026-08-21")


def test_the_stale_gate_does_not_read_a_row_the_key_no_longer_reads(ranked):
    """AUTO.L's gross profit is from 2024-03-31, 873 days before the run.
    Under E6 that line made the name 'periods do not match' (K6); under E43
    nothing reads it, so it makes the name neither mixed nor stale. AUTO.L
    ranks on its EBIT and total assets of 2026-03-31, at place 4."""
    auto = ranked.scored["AUTO.L"]
    assert auto.quality_state == QUALITY_OK
    assert auto.inputs.ebit_period == auto.inputs.total_assets_period == date(2026, 3, 31)
    assert [r.ticker for r in ranked.main[:4]][-1] == "AUTO.L"
    assert ranked.scored["BAB.L"].quality_state == QUALITY_OK


def test_no_name_is_mixed_on_this_population_under_e43(ranked):
    """K6's guard still stands (tests/test_ranking.py exercises it); on the
    frozen 394 it has nothing to refuse once both lines are read from one
    statement date."""
    mixed = sorted(t for t, s in ranked.scored.items()
                   if s.quality_state == QUALITY_MIXED_PERIODS)
    assert mixed == []


# --- what the net actually catches -----------------------------------------


def test_putting_the_strict_ebit_label_back_in_front_changes_this_answer(monkeypatch):
    """The regression, executed rather than asserted -- now in the direction
    the fix moved away from.

    Until 2026-08-23 the set was ordered on COVERAGE, strict ``EBIT`` first.
    That is the order this test substitutes. Under E43 both legs read the
    numerator the swap changes, so it moves 319 of the 328 places and the
    top five with them. ROCK-B.CO is E8's own second-rung case --
    ``Operating Income`` 594m before the Russian write-down against ``EBIT``
    211m after it -- and with ``EBIT`` first it falls. 382 of the 394
    candidates carry both labels and 357 carry DIFFERENT numbers under the
    two, so this is a live risk and not a hypothetical one.
    """
    from vss import ranking

    candidates, records, table = load()
    before = [r.ticker for r in rank_frozen(candidates, records, table).main]

    monkeypatch.setattr(
        ranking, "EBIT_ALIASES",
        ("EBIT", "Operating Income", "Total Operating Income As Reported"),
    )
    after = [r.ticker for r in rank_frozen(candidates, records, table).main]

    assert after[:20] != [row[1] for row in TOP_TWENTY]
    moved = sum(1 for a, b in zip(after, before) if a != b)
    assert moved > 200, (
        f"only {moved} places moved; if the alias set has stopped mattering "
        f"this test no longer guards anything and should be re-measured"
    )
    assert before[:5] == [row[1] for row in TOP_FIVE]
    assert after[:5] != before[:5], (
        "the top five no longer moves under the alias swap; re-measure"
    )
    assert after.index("ROCK-B.CO") > before.index("ROCK-B.CO"), \
        "E8's second-rung case must fall when the write-down label leads"


def test_the_alias_is_chosen_at_the_newest_year_end_any_label_reports(ranked):
    """L3 part two, and the reason a blind reorder was not the fix.

    Nine of the 394 carry ``Total Operating Income As Reported`` for a year
    end between 2021 and 2024 while the other two labels carry 2025. Taking
    the first label present at whatever year IT ends in would hand them a
    figure up to five years old with a current one beside it in the store --
    and the staleness gate (L4) would then exclude EIGHT of them, one being
    NVR. The year is settled first; meaning decides within it.
    """
    for ticker in ("NVR", "UMI.BR", "NEXI.MI", "BKW.SW", "FRES.L",
                   "GPG.ST", "CATE.ST", "G24.DE"):
        scored = ranked.scored[ticker]
        assert scored.inputs.ebit_period == date(2025, 12, 31), ticker
        assert scored.inputs.ebit_label == "Operating Income", ticker
        assert scored.quality_state != QUALITY_STALE, f"{ticker} went stale"
    assert [s.ticker for s in ranked.stale] == STALE


def test_the_first_label_would_have_been_years_older_for_those_names():
    """Otherwise the test above proves nothing about the rule."""
    _, records, _ = load()
    for ticker, older in (("NVR", date(2024, 12, 31)),
                          ("CATE.ST", date(2021, 12, 31)),
                          ("FRES.L", date(2022, 12, 31))):
        found = records[ticker].latest("Total Operating Income As Reported")
        assert found is not None and found[0] == older, ticker


def test_one_figure_in_two_units_is_DATA_MISSING_and_says_so(ranked):
    """MONC.MI: Operating Income 913,356,000 and Total Operating Income As
    Reported 913,356 for the SAME 2025-12-31. Identical digits, ratio exactly
    1000. Which unit the statement meant is not readable off anything stored,
    so the EBIT is DATA MISSING -- K6's shape, not a guess at the other label.
    """
    scored = ranked.scored["MONC.MI"]
    assert scored.inputs.ebit is None
    assert scored.inputs.ebit_label is None
    assert scored.earnings_yield is None
    assert "one figure in two units" in scored.note
    assert "913,356,000" in scored.note and "913,356 " in scored.note
    assert scored.ticker in [s.ticker for s in ranked.unrankable]
    # E43: the quality leg reads the same EBIT, so it is withheld too --
    # counted as input missing, apart from the yield's own note.
    assert scored.quality_state == QUALITY_MISSING


def test_the_unit_check_fires_on_this_one_name_and_no_other(ranked):
    """The measured claim behind UNIT_TOLERANCE: over every pairwise alias
    ratio of the 394, MONC.MI is the only hit, and the next-nearest ratio in
    the whole set is a factor of 3.6 below the boundary."""
    hits = sorted(t for t, s in ranked.scored.items()
                  if s.inputs.ebit_unit_conflict is not None)
    assert hits == ["MONC.MI"]


def test_the_unit_check_does_not_move_with_its_tolerance():
    """If the answer depended on the tolerance, the tolerance would be a
    threshold. It does not: the same one name at 1e-9 and at 1e-2."""
    from vss import ranking

    _, records, _ = load()
    for tolerance in (1e-9, 1e-6, 1e-3, 1e-2):
        hits = sorted(
            ticker for ticker, record in records.items()
            if any(ranking.is_unit_slip(a, b, tolerance=tolerance)
                   for a, b in _alias_pairs(record))
        )
        assert hits == ["MONC.MI"], f"tolerance {tolerance} gives {hits}"


def _alias_pairs(record):
    """Every ordered pair of alias values sharing one year end."""
    from vss.ranking import EBIT_ALIASES

    found = {}
    for alias in EBIT_ALIASES:
        hit = record.latest(alias)
        if hit is not None:
            found[alias] = hit
    for first, (period, value) in found.items():
        for second, (other_period, other_value) in found.items():
            if first != second and period == other_period:
                yield value, other_value


def test_substituting_ebitda_for_ebit_changes_the_top_five(monkeypatch):
    """E5 forbade it and an AST test stops the module NAMING the field. This
    is the other half: what it would cost if it ever got in."""
    from vss import ranking

    monkeypatch.setattr(ranking, "EBIT_ALIASES", ("EBITDA", "EBIT"))
    candidates, records, table = load()
    wrong = rank_frozen(candidates, records, table)
    assert [r.ticker for r in wrong.main[:5]] != [row[1] for row in TOP_FIVE]


def test_reading_total_revenue_where_ebit_belongs_changes_it(monkeypatch):
    """The numerator both legs share, mis-picked from the top of the
    statement: a revenue-over-assets key puts COR, KR, UMI.BR, JMT.LS and
    NCC-B.ST first -- high-turnover, thin-margin businesses -- and none of
    the five names E43 ranks."""
    from vss import ranking

    monkeypatch.setattr(ranking, "EBIT_ALIASES", ("Total Revenue",))
    candidates, records, table = load()
    wrong = rank_frozen(candidates, records, table)
    assert [r.ticker for r in wrong.main[:5]] != [row[1] for row in TOP_FIVE]
    assert set(r.ticker for r in wrong.main[:5]).isdisjoint(row[1] for row in TOP_FIVE)


def test_reading_current_assets_where_total_assets_belongs_changes_it(monkeypatch):
    """A mis-picked balance post, executed the same way."""
    from vss import ranking

    monkeypatch.setattr(ranking, "TOTAL_ASSETS_LINE", "Current Assets")
    candidates, records, table = load()
    wrong = rank_frozen(candidates, records, table)
    assert [r.ticker for r in wrong.main[:5]] != [row[1] for row in TOP_FIVE]


def test_a_missing_exchange_rate_does_not_silently_become_parity(ranked):
    """Held here as well as in test_fx, because here it would move the answer.

    Roughly one candidate in seven reports in a currency it does not trade in.
    A rate read as 1.0 would rewrite those yields by the size of the rate.
    """
    candidates, records, _ = load()
    empty = rank_frozen(candidates, records, FxTable())
    ranked_tickers = {r.ticker for r in empty.main}
    assert len(ranked_tickers) < len(ranked.main), \
        "every name kept its yield with no rates at all"


def test_the_parts_bound_fires_on_no_name_and_the_vendors_refusals_were_artefacts(ranked):
    """L2, executed on the real 394 rather than on a hand-built record.

    Under rule 8 the bound judges totalCash - totalDebt against total assets,
    and not one of the 394 trips it. The four names it refused while it
    judged the VENDOR's enterpriseValue were artefacts of that field: their
    quote-summary net cash sits well inside their balance sheets, so each
    regains a yield from the parts -- LISP.SW at 4.3%, the figure the review
    computed by hand against the vendor's 27.6%.
    """
    refused = sorted(t for t, s in ranked.scored.items()
                     if s.earnings_yield is None and EV_IMPOSSIBLE_NOTE in s.note)
    assert refused == EV_REFUSED == []
    for ticker in VENDOR_EV_REFUSED:
        assert ranked.scored[ticker].earnings_yield is not None, ticker
        assert EV_IMPOSSIBLE_NOTE not in ranked.scored[ticker].note
    for ticker in ("CVNA", "LISP.SW", "SILEX.ST"):
        assert ranked.scored[ticker].quality_state == QUALITY_OK
        assert ticker in {r.ticker for r in ranked.main}
    # PLUS.L is Financial Services: it has no quality leg, so its yield puts
    # it in the earnings-yield-only section, where the vendor field had
    # kept it out.
    assert ranked.scored["PLUS.L"].quality_state == QUALITY_SECTOR
    assert "PLUS.L" in {r.ticker for r in ranked.yield_only}
    lisp = next(i for i, r in enumerate(ranked.main, start=1) if r.ticker == "LISP.SW")
    assert lisp == 183
    assert ranked.scored["LISP.SW"].earnings_yield == pytest.approx(0.0433, abs=5e-4)


def test_the_enterprise_value_bound_rejects_on_missing_data_never_on_value(ranked):
    """The column it lands in is the whole of the owner's condition on it."""
    reasons = ranked.tally.reasons
    assert not any(key.startswith("value:") and "net cash" in key for key in reasons)
    assert ranked.tally.rejected_on_missing == SECTIONS["unrankable"]
    # One name computed a quality leg and no yield, and the two facts are
    # counted apart rather than summed into one "not rankable" number:
    # KMAR.OL, for which the store holds no marketCap so no share count can
    # be re-priced (rule 8). MONC.MI, whose EBIT is DATA MISSING because two
    # labels for 2025-12-31 are one figure in two units (L3), has NEITHER
    # leg under E43, since both read the EBIT.
    assert reasons["missing:quality leg computed, no earnings yield"] == 1
    assert ranked.scored["KMAR.OL"].note == "no market cap"
    assert ranked.scored["KMAR.OL"].operating_profitability is not None


def test_lifting_the_parts_bound_changes_nothing_on_this_population(monkeypatch):
    """The cost of the check on the parts, executed rather than asserted:
    nil. It fires on no name of the 394, so the list is the same 322 with
    or without it. It is kept because the direction of the error it would
    catch -- a wrong totalCash floating a name up the list -- is the one
    the ordering cannot afford."""
    from vss import ranking

    monkeypatch.setattr(ranking, "implied_net_cash_note", lambda inputs, rate=None: None)
    candidates, records, table = load()
    unbounded = rank_frozen(candidates, records, table)
    assert len(unbounded.main) == SECTIONS["both legs"]
    assert [r.ticker for r in unbounded.main[:20]] == [row[1] for row in TOP_TWENTY]


def test_reading_the_vendors_enterprise_value_again_would_change_this_answer(monkeypatch):
    """The regression rule 8 exists to stop, executed. Divide by the vendor's
    field instead of the parts and LISP.SW is back on 27.4% -- the
    impossible figure L2 caught, yield rank 1, place 32 under E43 -- and the
    fifth name changes (NHY.OL for AUTO.L), on an enterprise value struck at
    a price of the vendor's choosing."""
    from vss import ranking

    def vendor(inputs, rate):
        if inputs.enterprise_value_quoted is None or rate is None:
            return ranking.EvParts(None, None, None, "no enterprise value")
        return ranking.EvParts(None, None, rate.convert(inputs.enterprise_value_quoted), None)

    monkeypatch.setattr(ranking, "enterprise_value_parts", vendor)
    monkeypatch.setattr(ranking, "implied_net_cash_note", lambda inputs, rate=None: None)
    candidates, records, table = load()
    wrong = rank_frozen(candidates, records, table)
    assert [r.ticker for r in wrong.main[:5]] != [row[1] for row in TOP_FIVE]
    assert wrong.main[4].ticker == "NHY.OL"
    lisp = next(r for r in wrong.main if r.ticker == "LISP.SW")
    assert lisp.ey_rank == 1
    assert lisp.scored.earnings_yield == pytest.approx(0.2743, abs=5e-4)


def test_the_listed_investment_companies_are_not_ranked_on_both_legs(ranked):
    """E46: Latour was ranked on both legs (place 263 on 2026-08-26) on a
    vendor string; on the frozen population it and Prosus are the two
    listed names, and both sit in the yield-only section, never written."""
    listed = sorted(t for t, s in ranked.scored.items()
                    if s.quality_state == QUALITY_INVESTMENT)
    assert listed == ["LATO-B.ST", "PRX.AS"]
    assert {r.ticker for r in ranked.main}.isdisjoint(listed)
    assert set(listed) <= {r.ticker for r in ranked.yield_only}
    for ticker in listed:
        assert ranked.scored[ticker].earnings_yield is not None
    # And an industrial the vendor types the same way is ranked.
    assert "LIFCO-B.ST" in {r.ticker for r in ranked.main}
