"""BUILD tool. Freezes the phase 5 acceptance fixture. Never called at runtime.

Writes ``tests/fixtures/ranking-acceptance/`` from a stored price snapshot,
fundamentals store and ranking run: the statement lines and quote-summary
fields the ranking key reads, the settled close of every candidate on the
run date, plus the exchange rates the run recorded.

READ THIS BEFORE RE-RUNNING IT.

The fixture is the INPUT to the acceptance test. The EXPECTED OUTPUT -- the
top five names and their placings -- is written out longhand in
``tests/test_ranking_acceptance.py`` and is not generated by anything. That is
deliberate. A test whose expectation is regenerated from the code it tests
proves the code agrees with itself. If the acceptance test fails, the question
is what changed in the key, not how to refresh the numbers.

Re-run this only to freeze a DIFFERENT run, or when a RULING has legitimately
moved the frozen head (SCREENER-REVIEW-3 build, 2026-08-26: item 1 put the
enterprise value on the settled close, which needs the closes and the
net-debt legs frozen here). When you do, work out the new expectation
INDEPENDENTLY from the frozen figures -- plain arithmetic over the CSVs, not
the module under test -- and state in the commit which ruling moved which
names.

AND MIND WHERE THE RATES COME FROM. The fx fixture is read out of a run
manifest, and ``ranking-manifest.json`` is REWRITTEN by every ``--rank`` run
of the same date. The 2026-08-21 fixture deliberately carries the two rate
dates 08-21 and 08-22 -- that is the evidence K7 was found on, and
``test_the_frozen_candidate_set_is_the_one_the_run_ranked`` asserts it. The
run of 2026-08-23 replayed a clean single-date manifest and overwrote
``ranking-manifest.json`` with it. So for 2026-08-21 the rates are taken from
``ranking-manifest-fetched-2026-08-22.json``, the original fetch kept under
its own name (it reproduces the committed fx fixture byte for byte), and
``--fx-manifest`` names the file for any other freeze.

THE FETCH-DAY QUOTE ON A STORE THAT PREDATES THE FIELD. Rule 8 of the ranking
implies the vendor's share count from ``marketCap / regularMarketPrice``, and
``regularMarketPrice`` was first stored on 2026-08-26. The 2026-08-21 store
carries no such row. It was fetched on SATURDAY 2026-08-22 at 17:24, after
every market had closed on the Friday, so the quote its marketCap embeds is
the close of 2026-08-21. THE PRICE SNAPSHOT DOES NOT HOLD IT for the European
names: their newest stored bar is 2026-08-20 (E11 recorded the same thing --
one run priced two candidates on two different days), so the snapshot's close
is what the CHAIN priced at, not what the VENDOR priced at. The two are kept
apart: ``closes-<asof>.csv`` is the snapshot's newest close at or before the
run date, and ``regularMarketPrice`` is read from
``data/screener_runs/<asof>/fetch-day-closes-<asof>.csv`` -- the vendor's own
history close of the run date, fetched once for the freeze and named as such
in the field's ``text`` column. That file is written only when the store's
``fetched_at`` is after the last close of the run date
(``metrics.settled_through``); a store fetched mid-session embeds a print
nothing recorded, and the tool refuses rather than invents.
"""

from __future__ import annotations

import argparse
import csv
import json
import sqlite3
import sys
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests" / "fixtures" / "ranking-acceptance"
sys.path.insert(0, str(ROOT))

from vss import metrics, snapshot  # noqa: E402

#: The lines the key reads, its alias alternatives, and the neighbours a
#: mis-picked balance post would land on. EBITDA is here so that a regression
#: substituting it for EBIT changes the answer rather than changing nothing.
LINES = (
    "EBIT", "Operating Income", "Total Operating Income As Reported", "EBITDA",
    "Gross Profit", "Total Revenue",
    "Total Assets", "Current Assets", "Current Liabilities", "Net PPE",
)
#: ``marketCap``, ``regularMarketPrice``, ``totalDebt`` and ``totalCash`` are
#: the PARTS the enterprise value is built from (rule 8). ``enterpriseValue``
#: is the vendor's memo, kept so a regression that reads it again changes the
#: answer rather than changing nothing.
FIELDS = ("sector", "financialCurrency", "currency", "enterpriseValue",
          "marketCap", "regularMarketPrice", "totalDebt", "totalCash")

FETCH_DAY_PRICE = "regularMarketPrice"
DEFAULT_FX = {"2026-08-21": "ranking-manifest-fetched-2026-08-22.json"}


def main(asof: str = "2026-08-21", fx_manifest: str | None = None) -> int:
    store = ROOT / "data" / "screener_snapshots" / asof / "fundamentals.sqlite"
    prices = ROOT / "data" / "screener_snapshots" / asof / "snapshot.sqlite"
    run = ROOT / "data" / "screener_runs" / asof
    if not store.exists():
        print(f"no fundamentals store at {store}", file=sys.stderr)
        return 1
    if not prices.exists():
        print(f"no price snapshot at {prices}", file=sys.stderr)
        return 1
    fx_name = fx_manifest or DEFAULT_FX.get(asof, "ranking-manifest.json")
    fx_path = run / fx_name
    if not fx_path.exists():
        print(f"no fx manifest at {fx_path}", file=sys.stderr)
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    run_date = date.fromisoformat(asof)

    # THE POPULATION IS THE FROZEN ONE. A re-freeze after a ruling keeps the
    # candidate set the fixture already pins -- ``ranking.csv`` of the same
    # date is rewritten by every later --rank run under whatever exclusion
    # list stood that day (the 2026-08-24 run of 08-21 ranked 389 names, the
    # frozen set is 394). A FIRST freeze takes the run's own list.
    frozen_status = OUT / f"status-{asof}.csv"
    if frozen_status.exists():
        tickers = sorted({row["ticker"] for row in
                          csv.DictReader(frozen_status.open(encoding="utf-8"))})
        print(f"population: the {len(tickers)} names already frozen in {frozen_status.name}")
    else:
        tickers = sorted({row["ticker"] for row in
                          csv.DictReader((run / "ranking.csv").open(encoding="utf-8"))})
        print(f"population: the {len(tickers)} names of {run / 'ranking.csv'}")
    con = sqlite3.connect(store)
    marks = ",".join("?" * len(tickers))

    # LATEST period per (ticker, line). ``latest()`` reads no further back, so
    # older periods would bloat the fixture without changing an answer.
    rows = []
    for line in LINES:
        for ticker, statement, period, value in con.execute(
            f"select ticker, statement, max(period_end), value "
            f"from fundamentals_series "
            f"where line = ? and value is not null and ticker in ({marks}) "
            f"group by ticker", (line, *tickers)
        ):
            rows.append((ticker, statement, line, period, value))
    rows.sort()
    with (OUT / f"series-{asof}.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["ticker", "statement", "line", "period_end", "value"])
        writer.writerows((t, s, l, p, repr(v)) for t, s, l, p, v in rows)

    # --- the settled close of every candidate on the run date ---------------
    closes: dict[str, tuple[date, float]] = {}
    for ticker in tickers:
        frame = snapshot.read_prices(prices, ticker)
        computed = metrics.compute(frame, run_date) if frame is not None else metrics.Metrics()
        if computed.last_close is not None and computed.last_close_date is not None:
            closes[ticker] = (computed.last_close_date, computed.last_close)
    with (OUT / f"closes-{asof}.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["ticker", "close_date", "close"])
        writer.writerows((t, d.isoformat(), repr(c))
                         for t, (d, c) in sorted(closes.items()))

    field_rows = sorted(con.execute(
        f"select ticker, name, status, number, text from fundamentals_fields "
        f"where name in ({','.join('?' * len(FIELDS))}) and ticker in ({marks})",
        (*FIELDS, *tickers)
    ))

    # --- a store that predates the fetch-day quote -------------------------
    stored_price = {t for t, name, *_ in field_rows if name == FETCH_DAY_PRICE}
    if not stored_price:
        manifest = dict(con.execute("select key, value from manifest").fetchall())
        fetched_at = datetime.fromisoformat(manifest["fetched_at"]).astimezone()
        settled = metrics.settled_through(fetched_at)
        if settled < run_date:
            print(f"{store}: fetched {fetched_at.isoformat()} BEFORE the last close "
                  f"of {asof}, so its marketCap embeds a live print nothing "
                  f"recorded; refusing to invent {FETCH_DAY_PRICE}", file=sys.stderr)
            return 1
        fetch_day = run / f"fetch-day-closes-{asof}.csv"
        if not fetch_day.exists():
            print(f"{store} predates {FETCH_DAY_PRICE} and {fetch_day} is not there: "
                  f"write the vendor's history close of {asof} per ticker to it "
                  f"(ticker,close_date,close,source) before freezing", file=sys.stderr)
            return 1
        vendor_close: dict[str, tuple[str, float, str]] = {
            row["ticker"]: (row["close_date"], float(row["close"]), row["source"])
            for row in csv.DictReader(fetch_day.open(encoding="utf-8"))
        }
        for ticker in tickers:
            hit = vendor_close.get(ticker)
            if hit is not None and hit[0] == asof:
                note = (f"{hit[2]}: the store predates the field and was fetched "
                        f"{fetched_at.isoformat(timespec='minutes')}, after the last "
                        f"close of {asof}, so the vendor's marketCap embeds this close")
                field_rows.append((ticker, FETCH_DAY_PRICE, "OK", hit[1], note))
            else:
                field_rows.append((ticker, FETCH_DAY_PRICE, "NO_DATA", None,
                                   f"no vendor close of {asof} in {fetch_day.name}"))
        field_rows.sort()

    with (OUT / f"fields-{asof}.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["ticker", "name", "status", "number", "text"])
        for ticker, name, status, number, text in field_rows:
            writer.writerow([ticker, name, status,
                             "" if number is None else repr(number), text or ""])

    status_rows = sorted(con.execute(
        f"select ticker, status, error from fundamentals_status "
        f"where ticker in ({marks})", tickers))
    with (OUT / f"status-{asof}.csv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(["ticker", "status", "error"])
        writer.writerows((t, s, e or "") for t, s, e in status_rows)

    manifest = json.loads(fx_path.read_text(encoding="utf-8"))
    (OUT / f"fx-{asof}.json").write_text(
        json.dumps({"asof": asof, "fx": manifest["fx"]}, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"{len(tickers)} tickers, {len(rows)} series rows, "
          f"{len(field_rows)} field rows, {len(closes)} closes -> {OUT}")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("asof", nargs="?", default="2026-08-21")
    parser.add_argument("--fx-manifest", default=None,
                        help="manifest file under data/screener_runs/<asof>/ to "
                             "take the rates from")
    args = parser.parse_args()
    raise SystemExit(main(args.asof, args.fx_manifest))
